/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef, useEffect, useState } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';
import { useFrame, useThree } from '@react-three/fiber';
import RoomScene from '../assets/3d/office2.glb';
import { a } from '@react-spring/three';
import { Box3, Vector3, Raycaster, Vector2 } from 'three';
import { useNavigate } from 'react-router-dom';

const Room = ({ isRotating, setIsRotating, setCurrentStage, ...props }) => {
  const RoomRef = useRef();
  const { gl, viewport, camera, scene } = useThree();
  const { nodes, materials, animations } = useGLTF(RoomScene);
  const { actions } = useAnimations(animations, RoomRef);
  const [movement, setMovement] = useState({
    forward: false,
    backward: false,
    left: false,
    right: false,
    up: false,
    down: false,
  });

  const raycaster = new Raycaster();
  const mouse = new Vector2();
  const lastX = useRef(0);
  const rotationSpeed = useRef(0);
  const dampingFactor = 0.95;

  const history = useNavigate(); // For navigating to another page
  const [boundaries, setBoundaries] = useState({
    xMin: -Infinity,
    xMax: Infinity,
    yMin: -Infinity,
    yMax: Infinity,
    zMin: -Infinity,
    zMax: Infinity,
  });

  useEffect(() => {
    if (RoomRef.current) {
      const box = new Box3().setFromObject(RoomRef.current);
      const size = new Vector3();
      const center = new Vector3();
      box.getSize(size);
      box.getCenter(center);

      setBoundaries({
        xMin: center.x - size.x / 2,
        xMax: center.x + size.x / 2,
        yMin: center.y - size.y / 2,
        yMax: center.y + size.y / 2,
        zMin: center.z - size.z / 2,
        zMax: center.z + size.z / 2,
      });
    }
  }, [RoomRef]);

  const handlePointerDown = (e) => {
    e.stopPropagation();
    e.preventDefault();
    setIsRotating(true);
    const clientX = e.touches ? e.touches[0].clientX : e.clientX;
    lastX.current = clientX;
  };

  const handlePointerUp = (e) => {
    e.stopPropagation();
    e.preventDefault();
    setIsRotating(false);
  };

  const handlePointerMove = (e) => {
    e.stopPropagation();
    e.preventDefault();

    if (isRotating) {
      const clientX = e.touches ? e.touches[0].clientX : e.clientX;
      const delta = (clientX - lastX.current) / viewport.width;
      RoomRef.current.rotation.y += delta * 0.01 * Math.PI;
      lastX.current = clientX;
      rotationSpeed.current = delta * 0.01 * Math.PI;
    }
  };

  const handleKeyDown = (e) => {
    if (e.key === 'ArrowLeft') {
      setMovement((prev) => ({ ...prev, left: true }));
    } else if (e.key === 'ArrowRight') {
      setMovement((prev) => ({ ...prev, right: true }));
    } else if (e.key === 'ArrowUp') {
      setMovement((prev) => ({ ...prev, forward: true }));
    } else if (e.key === 'ArrowDown') {
      setMovement((prev) => ({ ...prev, backward: true }));
    } else if (e.key === 'w') {
      setMovement((prev) => ({ ...prev, up: true }));
    } else if (e.key === 's') {
      setMovement((prev) => ({ ...prev, down: true }));
    }else if (e.key === 'Enter') {
      window.open('https://realtime-code-editor-three.vercel.app/', '_blank');
    }
  };

  const handleKeyUp = (e) => {
    if (e.key === 'ArrowLeft') {
      setMovement((prev) => ({ ...prev, left: false }));
    } else if (e.key === 'ArrowRight') {
      setMovement((prev) => ({ ...prev, right: false }));
    } else if (e.key === 'ArrowUp') {
      setMovement((prev) => ({ ...prev, forward: false }));
    } else if (e.key === 'ArrowDown') {
      setMovement((prev) => ({ ...prev, backward: false }));
    } else if (e.key === 'w') {
      setMovement((prev) => ({ ...prev, up: false }));
    } else if (e.key === 's') {
      setMovement((prev) => ({ ...prev, down: false }));
    }
  };

  const handlePointerClick = (e) => {
    // Only perform raycasting when rotation is not active
    if (isRotating) return;

    // Convert mouse position to normalized coordinates
    mouse.x = (e.clientX / window.innerWidth) * 2 - 1;
    mouse.y = -(e.clientY / window.innerHeight) * 2 + 1;

    // Update raycaster to intersect with 3D objects
    raycaster.update();
    raycaster.setFromCamera(mouse, camera);

    // Get the objects the ray intersects
    const intersects = raycaster.intersectObjects(scene.children);

    if (intersects.length > 0) {
      const object = intersects[0].object;

      // Check if the clicked object has a specific identifier
      if (object.name === 'ClickableObject') { // Replace 'ClickableObject' with your object name
        // Navigate to another page
        history('/pages/About'); // Replace '/new-page' with the URL you want to navigate to
      }
    }
  };

  useEffect(() => {
    const canvas = gl.domElement;
    canvas.addEventListener('pointerdown', handlePointerDown);
    canvas.addEventListener('pointerup', handlePointerUp);
    canvas.addEventListener('pointermove', handlePointerMove);
    canvas.addEventListener('click', handlePointerClick); // Listen for click events
    document.addEventListener('keydown', handleKeyDown);
    document.addEventListener('keyup', handleKeyUp);

    return () => {
      canvas.removeEventListener('pointerdown', handlePointerDown);
      canvas.removeEventListener('pointerup', handlePointerUp);
      canvas.removeEventListener('pointermove', handlePointerMove);
      canvas.removeEventListener('click', handlePointerClick);
      document.removeEventListener('keydown', handleKeyDown);
      document.removeEventListener('keyup', handleKeyUp);
    };
  }, [gl, isRotating, camera]);

  useFrame(() => {
    const moveSpeed = 0.4;

    if (movement.forward) {
      camera.position.z = Math.max(boundaries.zMin, camera.position.z - moveSpeed);
    }
    if (movement.backward) {
      camera.position.z = Math.min(boundaries.zMax, camera.position.z + moveSpeed);
    }
    if (movement.left) {
      camera.position.x = Math.max(boundaries.xMin, camera.position.x - moveSpeed);
    }
    if (movement.right) {
      camera.position.x = Math.min(boundaries.xMax, camera.position.x + moveSpeed);
    }
    if (movement.up) {
      camera.position.y = Math.min(boundaries.yMax, camera.position.y + moveSpeed);
    }
    if (movement.down) {
      camera.position.y = Math.max(boundaries.yMin, camera.position.y - moveSpeed);
    }

    if (!isRotating) {
      rotationSpeed.current *= dampingFactor;
      if (Math.abs(rotationSpeed.current) < 0.001) {
        rotationSpeed.current = 0;
      }
      RoomRef.current.rotation.y += rotationSpeed.current;
    }
  });
  return (
       <a.group ref={RoomRef} {...props} >
    
   
    <a.group name="Scene">
        <mesh
          name="Object_23001"
          
          
          geometry={nodes.Object_23001.geometry}
          material={materials.Silicio}
        />
        <mesh
          name="Object_24001"
          
          
          geometry={nodes.Object_24001.geometry}
          material={materials.material}
        />
        <mesh
          name="BigWhiteTables_BigWhiteTable_0"
          
          
          geometry={nodes.BigWhiteTables_BigWhiteTable_0.geometry}
          material={materials.BigWhiteTable}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={0.826}
        />
        <mesh
          name="curtain_low001_Curtain_0"
          
          
          geometry={nodes.curtain_low001_Curtain_0.geometry}
          material={materials.Curtain}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={0.826}
        />
        <mesh
          name="Doors_Door_Solid_0"
          
          
          geometry={nodes.Doors_Door_Solid_0.geometry}
          material={materials.Door_Solid}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={0.826}
        />
        <mesh
          name="Floor002_carpet_0"
          
          
          geometry={nodes.Floor002_carpet_0.geometry}
          material={materials.carpet}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={0.826}
        />
        <mesh
          name="Floor002_woodFloor_0"
          
          
          geometry={nodes.Floor002_woodFloor_0.geometry}
          material={materials.woodFloor}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[0.826, 0.826, 0.569]}
        />
        <mesh
          name="Floor003_ceilingtiles_0"
          
          
          geometry={nodes.Floor003_ceilingtiles_0.geometry}
          material={materials.ceilingtiles}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={0.826}
        />
        <mesh
          name="Floor003_ceilingtiles_plain_0"
          
          
          geometry={nodes.Floor003_ceilingtiles_plain_0.geometry}
          material={materials.ceilingtiles_plain}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={0.826}
        />
        <mesh
          name="Pillar001_Walls_0"
          
          
          geometry={nodes.Pillar001_Walls_0.geometry}
          material={materials.Walls}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={0.826}
        />
        <mesh
          name="RoundWindowGlass001_glass_0"
          
          
          geometry={nodes.RoundWindowGlass001_glass_0.geometry}
          material={materials.glass}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={0.826}
        />
        <mesh
          name="RoundWindowMetal001_Metal_Black_0"
          
          
          geometry={nodes.RoundWindowMetal001_Metal_Black_0.geometry}
          material={materials.Metal_Black}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={0.826}
        />
        <mesh
          name="Shelving_shelving_0"
          
          
          geometry={nodes.Shelving_shelving_0.geometry}
          material={materials.shelving}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={0.826}
        />
        <mesh
          name="SmallWhiteTables_SmallWhiteTable_low001_0"
          
          
          geometry={nodes.SmallWhiteTables_SmallWhiteTable_low001_0.geometry}
          material={materials['SmallWhiteTable_low.001']}
          position={[0.068, -0.011, -0.332]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[0.826, 0.826, 1.214]}
        />
        <mesh
          name="back2_aiStandardSurface1_0"
          
          
          geometry={nodes.back2_aiStandardSurface1_0.geometry}
          material={materials.aiStandardSurface1}
          position={[0.221, 0.545, -1.626]}
          rotation={[-Math.PI, 0.203, -Math.PI]}
          scale={[-0.024, 0.02, 0.029]}
        />
        <mesh
          name="_Ceiling_Light_light_0"
          
          
          geometry={nodes._Ceiling_Light_light_0.geometry}
          material={materials.light}
          position={[0.913, 2.051, -1.223]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          name="_Ceiling_Light_metal1_0"
          
          
          geometry={nodes._Ceiling_Light_metal1_0.geometry}
          material={materials.metal1}
          position={[0.913, 2.051, -1.223]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          name="_Ceiling_Light_metal2_0"
          
          
          geometry={nodes._Ceiling_Light_metal2_0.geometry}
          material={materials.metal2}
          position={[0.913, 2.051, -1.223]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          name="_Ceiling_Light_metal3_0"
          
          
          geometry={nodes._Ceiling_Light_metal3_0.geometry}
          material={materials.metal3}
          position={[0.913, 2.051, -1.223]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <a.group name="RootNode010" position={[0.098, 0.594, -2.296]} scale={[0.063, 0.057, 0.056]}>
          <a.group name="pCube59" position={[0.009, 6.603, 4.885]} scale={[1.331, 1.331, 0.719]}>
            <mesh
              name="pCube59_pc_modelagem_blinn5_0"
              
              
              geometry={nodes.pCube59_pc_modelagem_blinn5_0.geometry}
              material={materials.pc_modelagem_blinn5}
            />
          </a.group>
          <a.group name="pCube63" position={[0.009, 7.421, -5.278]} scale={[1.331, 1.331, 0.719]}>
            <mesh
              name="pCube63_pc_modelagem_blinn5_0"
              
              
              geometry={nodes.pCube63_pc_modelagem_blinn5_0.geometry}
              material={materials.pc_modelagem_blinn5}
            />
          </a.group>
          <a.group name="pCube66" position={[0.009, 5.003, -5.278]} scale={[1.331, 1.331, 0.719]}>
            <mesh
              name="pCube66_pc_modelagem_blinn5_0"
              
              
              geometry={nodes.pCube66_pc_modelagem_blinn5_0.geometry}
              material={materials.pc_modelagem_blinn5}
            />
          </a.group>
          <a.group name="pCube69" position={[0.009, 2.636, -5.278]} scale={[1.331, 1.331, 0.719]}>
            <mesh
              name="pCube69_pc_modelagem_blinn5_0"
              
              
              geometry={nodes.pCube69_pc_modelagem_blinn5_0.geometry}
              material={materials.pc_modelagem_blinn5}
            />
          </a.group>
          <a.group
            name="pCube74"
            position={[0.853, 4.168, -0.807]}
            rotation={[1.549, -1.571, 0]}
            scale={0.725}>
            <mesh
              name="pCube74_pc_modelagem_blinn5_0"
              
              
              geometry={nodes.pCube74_pc_modelagem_blinn5_0.geometry}
              material={materials.pc_modelagem_blinn5}
            />
          </a.group>
          <a.group
            name="pCube87"
            position={[0.853, 4.168, 0.841]}
            rotation={[-2.427, -1.571, 0]}
            scale={0.725}>
            <mesh
              name="pCube87_pc_modelagem_blinn5_0"
              
              
              geometry={nodes.pCube87_pc_modelagem_blinn5_0.geometry}
              material={materials.pc_modelagem_blinn5}
            />
          </a.group>
          <a.group
            name="pCube88"
            position={[0.853, 4.168, 2.474]}
            rotation={[-2.427, -1.571, 0]}
            scale={0.725}>
            <mesh
              name="pCube88_pc_modelagem_blinn5_0"
              
              
              geometry={nodes.pCube88_pc_modelagem_blinn5_0.geometry}
              material={materials.pc_modelagem_blinn5}
            />
          </a.group>
          <a.group name="polySurface24003" position={[0.162, 7.566, 2.373]}>
            <mesh
              name="polySurface24_pc_modelagem_blinn5_0"
              
              
              geometry={nodes.polySurface24_pc_modelagem_blinn5_0.geometry}
              material={materials.pc_modelagem_blinn5}
            />
          </a.group>
          <a.group name="polySurface7002" position={[0.162, 7.566, -0.208]}>
            <mesh
              name="polySurface7_pc_modelagem_blinn5_0"
              
              
              geometry={nodes.polySurface7_pc_modelagem_blinn5_0.geometry}
              material={materials.pc_modelagem_blinn5}
            />
          </a.group>
        </a.group>
        <mesh
          name="polySurface2_aiStandardSurface7_0"
          
          
          geometry={nodes.polySurface2_aiStandardSurface7_0.geometry}
          material={materials.aiStandardSurface7}
          position={[-0.06, 0.622, -2.312]}
          scale={[0.08, 0.05, 0.047]}
        />
        <mesh
          name="polySurface2_lambert25_0"
          
          
          geometry={nodes.polySurface2_lambert25_0.geometry}
          material={materials.lambert25}
          position={[-0.06, 0.622, -2.312]}
          scale={[0.08, 0.05, 0.047]}
        />
        <mesh
          name="pCube103_aiStandardSurface6_0"
          
          
          geometry={nodes.pCube103_aiStandardSurface6_0.geometry}
          material={materials.aiStandardSurface6}
          position={[0.103, 0.564, -2.425]}
          scale={[0.069, 0.062, 0.095]}
        />
        <mesh
          name="pCube104_lambert21_0"
          
          
          geometry={nodes.pCube104_lambert21_0.geometry}
          material={materials.lambert21}
          position={[0.069, 0.959, -2.263]}
          scale={[0.043, 0.119, 0.006]}
        />
        <mesh
          name="pCube104_lambert27_0"
          
          
          geometry={nodes.pCube104_lambert27_0.geometry}
          material={materials.lambert27}
          position={[0.069, 0.959, -2.263]}
          scale={[0.043, 0.119, 0.006]}
        />
        <mesh
          name="pCube107_aiStandardSurface2_0"
          
          
          geometry={nodes.pCube107_aiStandardSurface2_0.geometry}
          material={materials.aiStandardSurface2}
          position={[0.098, 0.595, -2.297]}
          scale={[0.063, 0.057, 0.056]}
        />
        <mesh
          name="pCube110_lambert31_0"
          
          
          geometry={nodes.pCube110_lambert31_0.geometry}
          material={materials.lambert31}
          position={[0.226, 0.922, -2.621]}
          scale={[0.063, 0.057, 0.056]}
        />
        <mesh
          name="pCube112_lambert28_0"
          
          
          geometry={nodes.pCube112_lambert28_0.geometry}
          material={materials.lambert28}
          position={[0.033, 0.887, -2.368]}
          scale={[0.006, 0.064, 0.043]}
        />
        <mesh
          name="pCube112_lambert29_0"
          
          
          geometry={nodes.pCube112_lambert29_0.geometry}
          material={materials.lambert29}
          position={[0.033, 0.887, -2.368]}
          scale={[0.006, 0.064, 0.043]}
        />
        <mesh
          name="pCube116_blinn25_0"
          
          
          geometry={nodes.pCube116_blinn25_0.geometry}
          material={materials.blinn25}
          position={[0.032, 0.92, -2.357]}
          scale={[0.001, 0.003, 0.005]}
        />
        <mesh
          name="pCube116_lambert30_0"
          
          
          geometry={nodes.pCube116_lambert30_0.geometry}
          material={materials.lambert30}
          position={[0.032, 0.92, -2.357]}
          scale={[0.001, 0.003, 0.005]}
        />
        <mesh
          name="pCube12_aiStandardSurface11_0"
          
          
          geometry={nodes.pCube12_aiStandardSurface11_0.geometry}
          material={materials.aiStandardSurface11}
          position={[0.098, 1.088, -2.224]}
          scale={[0.207, 0.034, 0.406]}
        />
        <mesh
          name="pCube121_blinn26_0"
          
          
          geometry={nodes.pCube121_blinn26_0.geometry}
          material={materials.blinn26}
          position={[0.172, 0.799, -2.212]}
          scale={[0.025, 0.022, 0.022]}
        />
        <mesh
          name="pCube16_pc_modelagem_lambert11_0"
          
          
          geometry={nodes.pCube16_pc_modelagem_lambert11_0.geometry}
          material={materials.pc_modelagem_lambert11}
          position={[0.098, 0.614, -2.492]}
          scale={[0.055, 0.053, 0.021]}
        />
        <mesh
          name="pCube17_aiStandardSurface4_0"
          
          
          geometry={nodes.pCube17_aiStandardSurface4_0.geometry}
          material={materials.aiStandardSurface4}
          position={[0.094, 0.892, -2.603]}
          scale={[0.168, 0.429, 0.003]}
        />
        <mesh
          name="pCube18_pc_modelagem_lambert13_0"
          
          
          geometry={nodes.pCube18_pc_modelagem_lambert13_0.geometry}
          material={materials.pc_modelagem_lambert13}
          position={[0.036, 0.928, -2.212]}
          scale={[0.012, 0.225, 0.251]}
        />
        <mesh
          name="pCube24_lambert35_0"
          
          
          geometry={nodes.pCube24_lambert35_0.geometry}
          material={materials.lambert35}
          position={[0.107, 1.063, -2.308]}
          scale={[0.15, 0.033, 0.127]}
        />
        <mesh
          name="pCube25_lambert15_0"
          
          
          geometry={nodes.pCube25_lambert15_0.geometry}
          material={materials.lambert15}
          position={[0.12, 0.827, -2.062]}
          scale={[0.144, 0.142, 0.064]}
        />
        <mesh
          name="pCube25_pc_modelagem_lambert14_0"
          
          
          geometry={nodes.pCube25_pc_modelagem_lambert14_0.geometry}
          material={materials.pc_modelagem_lambert14}
          position={[0.12, 0.827, -2.062]}
          scale={[0.144, 0.142, 0.064]}
        />
        <mesh
          name="pCube29_pc_modelagem_lambert7_0"
          
          
          geometry={nodes.pCube29_pc_modelagem_lambert7_0.geometry}
          material={materials.pc_modelagem_lambert7}
          position={[0.176, 1.05, -2.105]}
          scale={[0.038, 0.008, 0.032]}
        />
        <mesh
          name="pCube38_lambert37_0"
          
          
          geometry={nodes.pCube38_lambert37_0.geometry}
          material={materials.lambert37}
          position={[0.089, 0.594, -2.076]}
          scale={[0.063, 0.057, 0.01]}
        />
        <mesh
          name="pCube39_lambert1_0"
          
          
          geometry={nodes.pCube39_lambert1_0.geometry}
          material={materials.lambert1}
          position={[0.088, 0.594, -2.07]}
          rotation={[-0.003, 0, 0]}
          scale={[0.063, 0.057, 0.007]}
        />
        <mesh
          name="pCube4_lambert36_0"
          
          
          geometry={nodes.pCube4_lambert36_0.geometry}
          material={materials.lambert36}
          position={[0.098, 0.707, -2.226]}
          scale={[0.207, 0.111, 0.389]}
        />
        <mesh
          name="pCube4_lambert44_0"
          
          
          geometry={nodes.pCube4_lambert44_0.geometry}
          material={materials.lambert44}
          position={[0.098, 0.707, -2.226]}
          scale={[0.207, 0.111, 0.389]}
        />
        <mesh
          name="pCube4_lambert45_0"
          
          
          geometry={nodes.pCube4_lambert45_0.geometry}
          material={materials.lambert45}
          position={[0.098, 0.707, -2.226]}
          scale={[0.207, 0.111, 0.389]}
        />
        <mesh
          name="pCube6_lambert16_0"
          
          
          geometry={nodes.pCube6_lambert16_0.geometry}
          material={materials.lambert16}
          position={[0.063, 0.95, -2.183]}
          scale={[0.038, 0.081, 0.081]}
        />
        <mesh
          name="pCube62_blinn24_0"
          
          
          geometry={nodes.pCube62_blinn24_0.geometry}
          material={materials.blinn24}
          position={[0.217, 0.882, -2.296]}
          rotation={[0.002, 0, 0]}
          scale={[0, 0.444, 0.528]}
        />
        <mesh
          name="pCube64_pc_modelagem_blinn16_0"
          
          
          geometry={nodes.pCube64_pc_modelagem_blinn16_0.geometry}
          material={materials.pc_modelagem_blinn16}
          position={[0.083, 0.641, -2.622]}
          scale={[0.063, 0.057, 0.008]}
        />
        <mesh
          name="pCube78_pc_modelagem_blinn1_0"
          
          
          geometry={nodes.pCube78_pc_modelagem_blinn1_0.geometry}
          material={materials.pc_modelagem_blinn1}
          position={[0.099, 0.974, -2.016]}
          scale={[0.168, 0.141, 0.003]}
        />
        <mesh
          name="pCube86_pc_modelagem_blinn17_0"
          
          
          geometry={nodes.pCube86_pc_modelagem_blinn17_0.geometry}
          material={materials.pc_modelagem_blinn17}
          position={[0.099, 0.881, -2.572]}
          scale={[0.214, 0.444, 0.005]}
        />
        <mesh
          name="pCylinder53_aiStandardSurface9_0"
          
          
          geometry={nodes.pCylinder53_aiStandardSurface9_0.geometry}
          material={materials.aiStandardSurface9}
          position={[0.078, 0.915, -1.939]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[0.029, 0.032, 0.032]}
        />
        <mesh
          name="pCylinder57_pc_modelagem_blinn18_0"
          
          
          geometry={nodes.pCylinder57_pc_modelagem_blinn18_0.geometry}
          material={materials.pc_modelagem_blinn18}
          position={[0.101, 1.016, -2.592]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.024, 0.002, 0.02]}
        />
        <mesh
          name="pCylinder63_pc_modelagem_blinn12_0"
          
          
          geometry={nodes.pCylinder63_pc_modelagem_blinn12_0.geometry}
          material={materials.pc_modelagem_blinn12}
          position={[0.01, 0.604, -2.296]}
          scale={[0.046, 0.057, 0.056]}
        />
        <mesh
          name="pCylinder72_aiStandardSurface5_0"
          
          
          geometry={nodes.pCylinder72_aiStandardSurface5_0.geometry}
          material={materials.aiStandardSurface5}
          position={[0.098, 0.669, -2.313]}
          scale={[0.063, 0.044, 0.043]}
        />
        <mesh
          name="pCylinder73_lambert33_0"
          
          
          geometry={nodes.pCylinder73_lambert33_0.geometry}
          material={materials.lambert33}
          position={[0.005, 0.628, -2.549]}
          scale={[0.011, 0.01, 0.009]}
        />
        <mesh
          name="pCylinder77_lambert32_0"
          
          
          geometry={nodes.pCylinder77_lambert32_0.geometry}
          material={materials.lambert32}
          position={[0.206, 1.077, -2.538]}
          rotation={[0, 0, Math.PI / 2]}
          scale={[0.005, 0.013, 0.005]}
        />
        <mesh
          name="pCylinder83_lambert43_0"
          
          
          geometry={nodes.pCylinder83_lambert43_0.geometry}
          material={materials.lambert43}
          position={[0.105, 0.771, -2.296]}
          scale={[0.014, 0.012, 0.012]}
        />
        <a.group
          name="RootNode011"
          position={[0.16, 0.612, 0.997]}
          rotation={[Math.PI, 0.091, -Math.PI]}
          scale={[0.063, 0.057, 0.056]}>
          <a.group name="pCube59001" position={[0.009, 6.603, 4.885]} scale={[1.331, 1.331, 0.719]}>
            <mesh
              name="pCube59_pc_modelagem_blinn5_0001"
              
              
              geometry={nodes.pCube59_pc_modelagem_blinn5_0001.geometry}
              material={materials.pc_modelagem_blinn5}
            />
          </a.group>
          <a.group name="pCube63001" position={[0.009, 7.421, -5.278]} scale={[1.331, 1.331, 0.719]}>
            <mesh
              name="pCube63_pc_modelagem_blinn5_0001"
              
              
              geometry={nodes.pCube63_pc_modelagem_blinn5_0001.geometry}
              material={materials.pc_modelagem_blinn5}
            />
          </a.group>
          <a.group name="pCube66001" position={[0.009, 5.003, -5.278]} scale={[1.331, 1.331, 0.719]}>
            <mesh
              name="pCube66_pc_modelagem_blinn5_0001"
              
              
              geometry={nodes.pCube66_pc_modelagem_blinn5_0001.geometry}
              material={materials.pc_modelagem_blinn5}
            />
          </a.group>
          <a.group name="pCube69001" position={[0.009, 2.636, -5.278]} scale={[1.331, 1.331, 0.719]}>
            <mesh
              name="pCube69_pc_modelagem_blinn5_0001"
              
              
              geometry={nodes.pCube69_pc_modelagem_blinn5_0001.geometry}
              material={materials.pc_modelagem_blinn5}
            />
          </a.group>
          <a.group
            name="pCube74001"
            position={[0.853, 4.168, -0.807]}
            rotation={[1.549, -1.571, 0]}
            scale={0.725}>
            <mesh
              name="pCube74_pc_modelagem_blinn5_0001"
              
              
              geometry={nodes.pCube74_pc_modelagem_blinn5_0001.geometry}
              material={materials.pc_modelagem_blinn5}
            />
          </a.group>
          <a.group
            name="pCube87001"
            position={[0.853, 4.168, 0.841]}
            rotation={[-2.427, -Math.PI / 2, 0]}
            scale={0.725}>
            <mesh
              name="pCube87_pc_modelagem_blinn5_0001"
              
              
              geometry={nodes.pCube87_pc_modelagem_blinn5_0001.geometry}
              material={materials.pc_modelagem_blinn5}
            />
          </a.group>
          <a.group
            name="pCube88001"
            position={[0.853, 4.168, 2.474]}
            rotation={[-2.427, -Math.PI / 2, 0]}
            scale={0.725}>
            <mesh
              name="pCube88_pc_modelagem_blinn5_0001"
              
              
              geometry={nodes.pCube88_pc_modelagem_blinn5_0001.geometry}
              material={materials.pc_modelagem_blinn5}
            />
          </a.group>
          <a.group name="polySurface24006" position={[0.162, 7.566, 2.373]}>
            <mesh
              name="polySurface24_pc_modelagem_blinn5_0001"
              
              
              geometry={nodes.polySurface24_pc_modelagem_blinn5_0001.geometry}
              material={materials.pc_modelagem_blinn5}
            />
          </a.group>
          <a.group name="polySurface7005" position={[0.162, 7.566, -0.208]}>
            <mesh
              name="polySurface7_pc_modelagem_blinn5_0001"
              
              
              geometry={nodes.polySurface7_pc_modelagem_blinn5_0001.geometry}
              material={materials.pc_modelagem_blinn5}
            />
          </a.group>
        </a.group>
        <mesh
          name="Object_58"
          
          
          geometry={nodes.Object_58.geometry}
          material={materials.material_14}
          position={[1.913, 0.711, -2.45]}
          rotation={[Math.PI, -1.53, Math.PI]}
          scale={1.156}
        />
        <mesh
          name="Object_10"
          
          
          geometry={nodes.Object_10.geometry}
          material={materials.Plastic}
          position={[1.983, 0.863, -2.525]}
          rotation={[-Math.PI / 2, 0, -1.612]}
        />
        <mesh
          name="Object_12"
          
          
          geometry={nodes.Object_12.geometry}
          material={materials.Emission}
          position={[1.983, 0.863, -2.525]}
          rotation={[-Math.PI / 2, 0, -1.612]}
        />
        <mesh
          name="Object_8"
          
          
          geometry={nodes.Object_8.geometry}
          material={materials.RTX_Material}
          position={[1.983, 0.863, -2.525]}
          rotation={[-Math.PI / 2, 0, -1.612]}
        />
        <mesh
          name="Object_9"
          
          
          geometry={nodes.Object_9.geometry}
          material={materials.Metallic}
          position={[1.983, 0.863, -2.525]}
          rotation={[-Math.PI / 2, 0, -1.612]}
        />
        <mesh
          name="Object_60"
          
          
          geometry={nodes.Object_60.geometry}
          material={materials.material_15}
          position={[1.955, 0.709, -2.398]}
          rotation={[Math.PI, -1.53, Math.PI]}
          scale={[0.897, 1, 1]}
        />
        <mesh
          name="Object_68"
          
          
          geometry={nodes.Object_68.geometry}
          material={materials.Case}
          position={[1.859, 0.996, -2.513]}
          rotation={[Math.PI, -1.53, Math.PI]}
          scale={1.24}
        />
        <mesh
          name="Object_4"
          
          
          geometry={nodes.Object_4.geometry}
          material={materials.AMD_material}
          position={[1.939, 0.971, -2.387]}
          rotation={[-Math.PI / 2, 0, -1.612]}
        />
        <mesh
          name="Object_5"
          
          
          geometry={nodes.Object_5.geometry}
          material={materials.AMDCenter}
          position={[1.939, 0.971, -2.387]}
          rotation={[-Math.PI / 2, 0, -1.612]}
        />
        <mesh
          name="Object_18"
          
          
          geometry={nodes.Object_18.geometry}
          material={materials.MotherboardRetro}
          position={[1.969, 0.924, -2.379]}
          rotation={[Math.PI, -1.53, Math.PI]}
        />
        <mesh
          name="Object_22"
          
          
          geometry={nodes.Object_22.geometry}
          material={materials.RoughPlastic}
          position={[1.941, 0.97, -2.32]}
          rotation={[0, -0.041, Math.PI / 2]}
        />
        <mesh
          name="Object_42"
          
          
          geometry={nodes.Object_42.geometry}
          material={materials.Motherboard}
          position={[1.981, 0.881, -2.42]}
          rotation={[Math.PI / 2, 0, 1.612]}
        />
        <mesh
          name="Object_49"
          
          
          geometry={nodes.Object_49.geometry}
          material={materials.Cable}
          position={[1.84, 0.846, -2.363]}
          rotation={[Math.PI, -1.53, Math.PI]}
        />
        <mesh
          name="Object_56"
          
          
          geometry={nodes.Object_56.geometry}
          material={materials.material_13}
          position={[1.959, 0.787, -2.488]}
          rotation={[0, 1.53, -3.142]}
        />
        <mesh
          name="Object_40"
          
          
          geometry={nodes.Object_40.geometry}
          material={materials.MotherBoardEmission}
          position={[1.981, 0.881, -2.422]}
          rotation={[Math.PI / 2, 0, 1.612]}
        />
        <mesh
          name="aorus_case_fans_aorus_case_fans_0"
          
          
          geometry={nodes.aorus_case_fans_aorus_case_fans_0.geometry}
          material={materials['Material.074_0']}
          position={[-0.498, 0.971, 1.838]}
          rotation={[0, -1.565, 0]}
          scale={[0.119, 0.132, 0.081]}
        />
        <mesh
          name="aorus_logotranspa_aorus_logotranspa_0"
          
          
          geometry={nodes.aorus_logotranspa_aorus_logotranspa_0.geometry}
          material={materials['Material.074_24']}
          position={[-0.296, 0.841, 1.793]}
          rotation={[Math.PI, -0.006, Math.PI]}
          scale={[0.006, 0.011, 0.01]}
        />
        <mesh
          name="BezierCircle_Material104_0"
          
          
          geometry={nodes.BezierCircle_Material104_0.geometry}
          material={materials['Material.104']}
          position={[-0.497, 0.994, 1.758]}
          rotation={[0, -1.565, -1.571]}
          scale={[0.007, 0.006, 0.004]}
        />
        <mesh
          name="BezierCurve_Material088_0"
          
          
          geometry={nodes.BezierCurve_Material088_0.geometry}
          material={materials['Material.088']}
          position={[-0.485, 0.909, 1.928]}
          rotation={[0, 0.006, -Math.PI / 2]}
          scale={[0.122, 0.074, 0.11]}
        />
        <mesh
          name="BezierCurve001_Material085_0"
          
          
          geometry={nodes.BezierCurve001_Material085_0.geometry}
          material={materials['Material.085']}
          position={[-0.389, 0.764, 1.794]}
          rotation={[1.164, 1.097, -3.017]}
          scale={[0.137, 0.126, 0.09]}
        />
        <mesh
          name="BezierCurve002_Material087_0"
          
          
          geometry={nodes.BezierCurve002_Material087_0.geometry}
          material={materials['Material.087']}
          position={[-0.408, 0.843, 1.93]}
          rotation={[1.164, 1.097, -3.017]}
          scale={[0.137, 0.126, 0.09]}
        />
        <mesh
          name="BezierCurve003_Material091_0"
          
          
          geometry={nodes.BezierCurve003_Material091_0.geometry}
          material={materials['Material.025']}
          position={[-0.317, 0.775, 1.119]}
          rotation={[-2.46, Math.PI / 2, 0]}
          scale={[0.113, 0.113, 0.073]}
        />
        <mesh
          name="bg2_bg2_0"
          
          
          geometry={nodes.bg2_bg2_0.geometry}
          material={materials['Material.074_29']}
          position={[-0.32, 0.857, 1.356]}
          rotation={[1.541, 1.426, -1.481]}
          scale={[0.123, 0.137, 0.085]}
        />
        <mesh
          name="Color-PewDiePie-Logo_Color-PewDiePie-Logo_0"
          
          
          geometry={nodes['Color-PewDiePie-Logo_Color-PewDiePie-Logo_0'].geometry}
          material={materials['Material.074_27']}
          position={[-0.53, 0.676, 1.479]}
          rotation={[-1.281, -0.364, -1.212]}
          scale={[0.013, 0.009, 0.014]}
        />
        <mesh
          name="Cube_Material_0"
          
          
          geometry={nodes.Cube_Material_0.geometry}
          material={materials['Material.001']}
          position={[-0.389, 0.619, 1.276]}
          rotation={[-Math.PI / 2, 0, 0.006]}
          scale={[-0.274, 0.802, 0.032]}
        />
        <mesh
          name="Cube001_Material055_0"
          
          
          geometry={nodes.Cube001_Material055_0.geometry}
          material={materials['Material.055']}
          position={[-0.333, 0.979, 1.118]}
          rotation={[-1.502, 0.029, -1.431]}
          scale={[0.346, 0.003, 0.216]}
        />
        <mesh
          name="Cube002_Material044_0"
          
          
          geometry={nodes.Cube002_Material044_0.geometry}
          material={materials['Material.044']}
          position={[-0.326, 0.94, 1.118]}
          rotation={[-1.453, 0.056, -1.341]}
          scale={[-0.341, 0.01, 0.175]}
        />
        <mesh
          name="Cube004_Material002_0"
          
          
          geometry={nodes.Cube004_Material002_0.geometry}
          material={materials['Material.002']}
          position={[-0.325, 0.84, 1.119]}
          rotation={[-1.502, 0.029, -1.431]}
          scale={[0.178, 0.013, 0.227]}
        />
        <mesh
          name="Cube005_Material003_0"
          
          
          geometry={nodes.Cube005_Material003_0.geometry}
          material={materials['Material.003']}
          position={[-0.297, 0.974, 1.121]}
          rotation={[-Math.PI / 2, 0, -1.565]}
          scale={[0.018, 0.021, 0.016]}
        />
        <mesh
          name="Cube006_Material043_0"
          
          
          geometry={nodes.Cube006_Material043_0.geometry}
          material={materials['Material.043']}
          position={[-0.285, 0.541, 1.118]}
          rotation={[-1.502, 0.029, -1.431]}
          scale={[0.043, 0.012, 0.625]}
        />
        <mesh
          name="Cube007_Material037_0"
          
          
          geometry={nodes.Cube007_Material037_0.geometry}
          material={materials['Material.037']}
          position={[-0.277, 0.663, 1.122]}
          rotation={[-Math.PI / 2, 0, -1.565]}
          scale={[-0.213, 0.04, 0.011]}
        />
        <mesh
          name="Cube008_Material036_0"
          
          
          geometry={nodes.Cube008_Material036_0.geometry}
          material={materials['Material.039']}
          position={[-0.377, 0.658, 0.951]}
          rotation={[-1.732, -0.049, -1.923]}
          scale={[0.059, 0.093, 0.008]}
        />
        <mesh
          name="Cube010_Material006_0"
          
          
          geometry={nodes.Cube010_Material006_0.geometry}
          material={materials['Material.006']}
          position={[-0.301, 0.658, 1.123]}
          rotation={[-Math.PI / 2, -0.002, -0.001]}
          scale={[0.032, 0.106, 0.006]}
        />
        <mesh
          name="Cube011_Material010_0"
          
          
          geometry={nodes.Cube011_Material010_0.geometry}
          material={materials['Material.074']}
          position={[-0.368, 0.863, 1.835]}
          rotation={[-Math.PI / 2, 0, -3.136]}
          scale={[0.129, 0.099, 0.191]}
        />
        <mesh
          name="Cube015_Material016_0"
          
          
          geometry={nodes.Cube015_Material016_0.geometry}
          material={materials['Material.074_1']}
          position={[-0.308, 0.892, 1.93]}
          rotation={[-Math.PI / 2, 0, 0.006]}
          scale={[-0.066, 0.001, 0.129]}
        />
        <mesh
          name="Cube016_Material017_0"
          
          
          geometry={nodes.Cube016_Material017_0.geometry}
          material={materials['Material.017']}
          position={[-0.49, 0.836, 1.838]}
          rotation={[0, -1.565, -1.571]}
          scale={[0.062, 0.056, 0.007]}
        />
        <mesh
          name="Cube020_Material020_0"
          
          
          geometry={nodes.Cube020_Material020_0.geometry}
          material={materials['Material.074_2']}
          position={[-0.36, 0.716, 1.846]}
          rotation={[-Math.PI / 2, 0, -3.136]}
          scale={[0.119, 0.081, 0.042]}
        />
        <mesh
          name="Cube025_Material023_0"
          
          
          geometry={nodes.Cube025_Material023_0.geometry}
          material={materials['Material.023']}
          position={[-0.308, 0.892, 1.93]}
          rotation={[-Math.PI / 2, 0, 0.006]}
          scale={[-0.066, 0.001, 0.129]}
        />
        <mesh
          name="Cube026_Material024_0"
          
          
          geometry={nodes.Cube026_Material024_0.geometry}
          material={materials['Material.024']}
          position={[-0.308, 0.892, 1.93]}
          rotation={[-Math.PI / 2, 0, 0.006]}
          scale={[-0.066, 0.001, 0.129]}
        />
        <mesh
          name="Cube027_Material008_0"
          
          
          geometry={nodes.Cube027_Material008_0.geometry}
          material={materials['Material.074_6']}
          position={[-0.359, 0.949, 1.92]}
          rotation={[-Math.PI / 2, 0, -3.136]}
          scale={[-0.001, 0.012, 0.054]}
        />
        <mesh
          name="Cube028_Material026_0"
          
          
          geometry={nodes.Cube028_Material026_0.geometry}
          material={materials['Material.074_7']}
          position={[-0.36, 0.949, 1.922]}
          rotation={[-Math.PI / 2, 0, -3.136]}
          scale={[-0.001, 0.011, 0.054]}
        />
        <mesh
          name="Cube045_Material027_0"
          
          
          geometry={nodes.Cube045_Material027_0.geometry}
          material={materials['Material.074_8']}
          position={[-0.274, 0.716, 1.774]}
          rotation={[-Math.PI / 2, 0, -3.136]}
          scale={[0.026, 0.006, 0.025]}
        />
        <mesh
          name="Cube046_Material034_0"
          
          
          geometry={nodes.Cube046_Material034_0.geometry}
          material={materials['Material.034']}
          position={[-0.291, 0.946, 1.851]}
          rotation={[-Math.PI / 2, 0, -3.136]}
          scale={[0.007, 0.047, 0.052]}
        />
        <mesh
          name="Cube048_Material035_0"
          
          
          geometry={nodes.Cube048_Material035_0.geometry}
          material={materials['Material.074_15']}
          position={[-0.311, 0.946, 1.851]}
          rotation={[-Math.PI / 2, 0, -3.136]}
          scale={[0.013, 0.043, 0.049]}
        />
        <mesh
          name="Cube049_Material040_0"
          
          
          geometry={nodes.Cube049_Material040_0.geometry}
          material={materials['Material.074_16']}
          position={[-0.311, 0.946, 1.851]}
          rotation={[-Math.PI / 2, 0, -3.136]}
          scale={[0.013, 0.043, 0.049]}
        />
        <mesh
          name="Cube051_Material042_0"
          
          
          geometry={nodes.Cube051_Material042_0.geometry}
          material={materials['Material.042']}
          position={[-0.311, 0.946, 1.851]}
          rotation={[-Math.PI / 2, 0, -3.136]}
          scale={[0.013, 0.043, 0.049]}
        />
        <mesh
          name="Cube053_Material048_0"
          
          
          geometry={nodes.Cube053_Material048_0.geometry}
          material={materials['Material.048']}
          position={[-0.308, 0.892, 1.93]}
          rotation={[-Math.PI / 2, 0, 0.006]}
          scale={[-0.066, 0.001, 0.129]}
        />
        <mesh
          name="Cube054_Material049_0"
          
          
          geometry={nodes.Cube054_Material049_0.geometry}
          material={materials['Material.049']}
          position={[-0.308, 0.892, 1.93]}
          rotation={[-Math.PI / 2, 0, 0.006]}
          scale={[-0.066, 0.001, 0.129]}
        />
        <mesh
          name="Cube055_Material054_0"
          
          
          geometry={nodes.Cube055_Material054_0.geometry}
          material={materials['Material.054']}
          position={[-0.34, 0.845, 1.854]}
          rotation={[-Math.PI / 2, 0, -3.136]}
          scale={[0.099, 0.06, 0.016]}
        />
        <mesh
          name="Cube056_Material061_0"
          
          
          geometry={nodes.Cube056_Material061_0.geometry}
          material={materials['Material.061']}
          position={[-0.337, 0.863, 1.854]}
          rotation={[-Math.PI / 2, 0, -3.136]}
          scale={[0.095, 0.057, 0.015]}
        />
        <mesh
          name="Cube057_Material059_0"
          
          
          geometry={nodes.Cube057_Material059_0.geometry}
          material={materials['Material.074_22']}
          position={[-0.337, 0.863, 1.854]}
          rotation={[-Math.PI / 2, 0, -3.136]}
          scale={[0.095, 0.057, 0.015]}
        />
        <mesh
          name="Cube058_Material063_0"
          
          
          geometry={nodes.Cube058_Material063_0.geometry}
          material={materials['Material.074_23']}
          position={[-0.34, 0.88, 1.853]}
          rotation={[-Math.PI / 2, 0, -3.136]}
          scale={[0.099, 0.06, 0.001]}
        />
        <mesh
          name="Cube059_Material058_0"
          
          
          geometry={nodes.Cube059_Material058_0.geometry}
          material={materials['Material.058']}
          position={[-0.337, 0.863, 1.854]}
          rotation={[-Math.PI / 2, 0, -3.136]}
          scale={[0.095, 0.057, 0.015]}
        />
        <mesh
          name="Cube060_Material062_0"
          
          
          geometry={nodes.Cube060_Material062_0.geometry}
          material={materials['Material.062']}
          position={[-0.34, 0.941, 1.795]}
          rotation={[Math.PI, -0.006, Math.PI]}
          scale={[0.099, 0.065, 0.001]}
        />
        <mesh
          name="Cube063_Material074_0"
          
          
          geometry={nodes.Cube063_Material074_0.geometry}
          material={materials['Material.074_25']}
          position={[-0.516, 0.659, 1.478]}
          rotation={[Math.PI / 2, 0, -0.006]}
          scale={[-0.032, 0.047, 0.028]}
        />
        <mesh
          name="Cube066_Material076_0"
          
          
          geometry={nodes.Cube066_Material076_0.geometry}
          material={materials['Material.076']}
          position={[-0.516, 0.659, 1.478]}
          rotation={[1.571, 0.012, 0]}
          scale={[-0.032, 0.047, 0.028]}
        />
        <mesh
          name="Cube067_Material075_0"
          
          
          geometry={nodes.Cube067_Material075_0.geometry}
          material={materials['Material.075']}
          position={[-0.516, 0.659, 1.478]}
          rotation={[Math.PI / 2, 0, -0.006]}
          scale={[-0.032, 0.047, 0.028]}
        />
        <mesh
          name="Cube068_Material092_0"
          
          
          geometry={nodes.Cube068_Material092_0.geometry}
          material={materials['Material.092']}
          position={[-0.53, 0.674, 1.479]}
          rotation={[-1.592, -0.306, -3.007]}
          scale={[0.005, 0.007, 0.003]}
        />
        <mesh
          name="Cube075_Material086_0"
          
          
          geometry={nodes.Cube075_Material086_0.geometry}
          material={materials['Material.074_26']}
          position={[-0.239, 0.857, 1.854]}
          rotation={[-Math.PI / 2, 0, -3.136]}
          scale={[0.001, 0.057, 0.022]}
        />
        <mesh
          name="Cube081_Material090_0"
          
          
          geometry={nodes.Cube081_Material090_0.geometry}
          material={materials['Material.090']}
          position={[-0.503, 0.678, 1.479]}
          rotation={[-1.583, 0.254, -3.028]}
          scale={[0.002, 0.001, 0.003]}
        />
        <mesh
          name="Cube088_Material098_0"
          
          
          geometry={nodes.Cube088_Material098_0.geometry}
          material={materials['Material.098']}
          position={[-0.507, 0.666, 1.457]}
          rotation={[-1.567, 0.143, -3.072]}
          scale={[0.004, 0.005, 0.002]}
        />
        <mesh
          name="Cylinder001_Material028_0"
          
          
          geometry={nodes.Cylinder001_Material028_0.geometry}
          material={materials['Material.074_11']}
          position={[-0.307, 0.759, 1.526]}
          rotation={[-1.695, -1.477, 2.811]}
          scale={[0.024, 0.021, 0.002]}
        />
        <mesh
          name="Cylinder005_Material041_0"
          
          
          geometry={nodes.Cylinder005_Material041_0.geometry}
          material={materials['Material.074_17']}
          position={[-0.312, 0.946, 1.852]}
          rotation={[0, -1.565, -1.571]}
          scale={[0.04, 0.036, 0.025]}
        />
        <mesh
          name="Cylinder006_Material050_0"
          
          
          geometry={nodes.Cylinder006_Material050_0.geometry}
          material={materials['Material.074_19']}
          position={[-0.276, 0.844, 1.853]}
          rotation={[-Math.PI / 2, 0, -3.136]}
          scale={[0.027, 0.042, 0.013]}
        />
        <mesh
          name="Cylinder007_Material051_0"
          
          
          geometry={nodes.Cylinder007_Material051_0.geometry}
          material={materials['Material.074_20']}
          position={[-0.339, 0.844, 1.853]}
          rotation={[-Math.PI / 2, 0, -3.136]}
          scale={[0.027, 0.042, 0.013]}
        />
        <mesh
          name="Cylinder010_Material077_0"
          
          
          geometry={nodes.Cylinder010_Material077_0.geometry}
          material={materials['Material.077']}
          position={[-0.491, 0.662, 1.479]}
          rotation={[Math.PI, -0.005, Math.PI]}
          scale={[0.009, 0.014, 0]}
        />
        <mesh
          name="Cylinder011_Material045_0"
          
          
          geometry={nodes.Cylinder011_Material045_0.geometry}
          material={materials['Material.045']}
          position={[-0.302, 0.915, 1.91]}
          rotation={[2.667, -0.005, -0.003]}
          scale={[0.002, 0.002, 0.019]}
        />
        <mesh
          name="Cylinder012_Material082_0"
          
          
          geometry={nodes.Cylinder012_Material082_0.geometry}
          material={materials['Material.082']}
          position={[-0.491, 0.662, 1.48]}
          rotation={[Math.PI, -0.005, Math.PI]}
          scale={[0.008, 0.013, 0.003]}
        />
        <mesh
          name="Cylinder013_Material094_0"
          
          
          geometry={nodes.Cylinder013_Material094_0.geometry}
          material={materials['Material.094']}
          position={[-0.494, 0.994, 1.758]}
          rotation={[0, -1.565, -1.571]}
          scale={[0.012, 0.011, 0.004]}
        />
        <mesh
          name="gallerymodel_gallerymodel_0"
          
          
          geometry={nodes.gallerymodel_gallerymodel_0.geometry}
          material={materials['Material.074_28']}
          position={[-0.332, 0.82, 0.794]}
          rotation={[2.687, 1.286, -2.617]}
          scale={[0.086, 0.098, 0.062]}
        />
        <mesh
          name="geforcertx_Material056_0"
          
          
          geometry={nodes.geforcertx_Material056_0.geometry}
          material={materials['Material.056']}
          position={[-0.261, 0.869, 1.793]}
          rotation={[Math.PI, -0.006, Math.PI]}
          scale={[0.008, 0.013, 0.012]}
        />
        <mesh
          name="gigabyte-logo_gigabyte-logo_0"
          
          
          geometry={nodes['gigabyte-logo_gigabyte-logo_0'].geometry}
          material={materials['Material.074_31']}
          position={[-0.314, 1.166, 1.357]}
          rotation={[1.608, 1.493, -1.573]}
          scale={[0.026, 0.029, 0.018]}
        />
        <mesh
          name="IOSHIELD_IOSHIELD_0"
          
          
          geometry={nodes.IOSHIELD_IOSHIELD_0.geometry}
          material={materials['Material.074_3']}
          position={[-0.238, 0.966, 1.91]}
          rotation={[-3.142, 1.565, 1.571]}
          scale={[0.032, 0.034, 0.024]}
        />
        <mesh
          name="maxresdefault_(1)_maxresdefault_(1)_0"
          
          
          geometry={nodes['maxresdefault_(1)_maxresdefault_(1)_0'].geometry}
          material={materials['Material.074_10']}
          position={[-0.497, 0.721, 1.838]}
          rotation={[0, -1.565, 0]}
          scale={[0.043, 0.048, 0.029]}
        />
        <mesh
          name="metal-mesh-500x500_metal-mesh-500x500_0"
          
          
          geometry={nodes['metal-mesh-500x500_metal-mesh-500x500_0'].geometry}
          material={materials['Material.074_5']}
          position={[-0.4, 1.054, 1.836]}
          rotation={[Math.PI / 2, 0, -0.006]}
          scale={[0.074, 0.147, 0.122]}
        />
        <mesh
          name="MOBOAORUSORANGETRANS_MOBOAORUSORANGETRANS_0"
          
          
          geometry={nodes.MOBOAORUSORANGETRANS_MOBOAORUSORANGETRANS_0.geometry}
          material={materials['Material.074_4']}
          position={[-0.256, 0.97, 1.912]}
          rotation={[-3.141, -0.005, -2.486]}
          scale={[0.006, 0.007, 0.007]}
        />
        <mesh
          name="MY_SCREEN_MY_SCREEN_0"
          
          
          geometry={nodes.MY_SCREEN_MY_SCREEN_0.geometry}
          material={materials['Material.074_30']}
          position={[-0.334, 0.985, 1.118]}
          rotation={[-1.462, -1.492, -1.427]}
          scale={[0.363, 0.422, 0.247]}
        />
        <mesh
          name="NVIDIA_LOGO_NVIDIA_LOGO_0"
          
          
          geometry={nodes.NVIDIA_LOGO_NVIDIA_LOGO_0.geometry}
          material={materials['Material.074_12']}
          position={[-0.432, 0.705, 1.765]}
          rotation={[Math.PI, -0.006, Math.PI]}
          scale={[0.034, 0.055, 0.05]}
        />
        <mesh
          name="Object_10_Tastatur_Unterseite_0"
          
          
          geometry={nodes.Object_10_Tastatur_Unterseite_0.geometry}
          material={materials.Tastatur_Unterseite}
          position={[-0.546, 0.66, 1.007]}
          rotation={[-3.142, 1.565, 0]}
          scale={[0.1, 0.111, 0.068]}
        />
        <mesh
          name="Object_101_Material067_0"
          
          
          geometry={nodes.Object_101_Material067_0.geometry}
          material={materials['Material.074_36']}
          position={[-0.546, 0.659, 1.007]}
          rotation={[-1.65, 1.469, -1.446]}
          scale={[0.1, 0.11, 0.068]}
        />
        <mesh
          name="Object_103_Material070_0"
          
          
          geometry={nodes.Object_103_Material070_0.geometry}
          material={materials['Material.074_39']}
          position={[-0.546, 0.659, 1.007]}
          rotation={[-1.65, 1.469, -1.446]}
          scale={[0.1, 0.11, 0.068]}
        />
        <mesh
          name="Object_105_Tasten_2_0"
          
          
          geometry={nodes.Object_105_Tasten_2_0.geometry}
          material={materials.Tasten_2}
          position={[-0.546, 0.659, 1.007]}
          rotation={[-1.65, 1.469, -1.446]}
          scale={[0.1, 0.11, 0.068]}
        />
        <mesh
          name="Object_109_Material069_0"
          
          
          geometry={nodes.Object_109_Material069_0.geometry}
          material={materials['Material.074_38']}
          position={[-0.546, 0.659, 1.007]}
          rotation={[-1.65, 1.469, -1.446]}
          scale={[0.1, 0.11, 0.068]}
        />
        <mesh
          name="Object_113_Material068_0"
          
          
          geometry={nodes.Object_113_Material068_0.geometry}
          material={materials['Material.074_37']}
          position={[-0.546, 0.659, 1.007]}
          rotation={[-1.65, 1.469, -1.446]}
          scale={[0.1, 0.11, 0.068]}
        />
        <mesh
          name="Object_115_Material057_0"
          
          
          geometry={nodes.Object_115_Material057_0.geometry}
          material={materials['Material.074_33']}
          position={[-0.546, 0.659, 1.007]}
          rotation={[-1.65, 1.469, -1.446]}
          scale={[0.1, 0.11, 0.068]}
        />
        <mesh
          name="Object_121_Material066_0"
          
          
          geometry={nodes.Object_121_Material066_0.geometry}
          material={materials['Material.074_35']}
          position={[-0.546, 0.659, 1.007]}
          rotation={[-1.65, 1.469, -1.446]}
          scale={[0.1, 0.11, 0.068]}
        />
        <mesh
          name="Object_131_Material060_0"
          
          
          geometry={nodes.Object_131_Material060_0.geometry}
          material={materials['Material.074_34']}
          position={[-0.546, 0.659, 1.007]}
          rotation={[-1.65, 1.469, -1.446]}
          scale={[0.1, 0.11, 0.068]}
        />
        <mesh
          name="Object_137_Material005_0"
          
          
          geometry={nodes.Object_137_Material005_0.geometry}
          material={materials['Material.074_32']}
          position={[-0.546, 0.659, 1.007]}
          rotation={[-1.65, 1.469, -1.446]}
          scale={[0.1, 0.11, 0.068]}
        />
        <mesh
          name="Object_14_Material004_0"
          
          
          geometry={nodes.Object_14_Material004_0.geometry}
          material={materials['Material.004']}
          position={[-0.546, 0.66, 1.007]}
          rotation={[-3.142, 1.565, 0]}
          scale={[0.1, 0.111, 0.068]}
        />
        <mesh
          name="Object_24_Tastatur_Seite_0"
          
          
          geometry={nodes.Object_24_Tastatur_Seite_0.geometry}
          material={materials.Tastatur_Seite}
          position={[-0.546, 0.66, 1.007]}
          rotation={[-3.142, 1.565, 0]}
          scale={[0.1, 0.111, 0.068]}
        />
        <mesh
          name="Object_30_Material007_0"
          
          
          geometry={nodes.Object_30_Material007_0.geometry}
          material={materials['Material.007']}
          position={[-0.546, 0.66, 1.007]}
          rotation={[-3.142, 1.565, 0]}
          scale={[0.1, 0.111, 0.068]}
        />
        <mesh
          name="Object_418_Tasten_0"
          
          
          geometry={nodes.Object_418_Tasten_0.geometry}
          material={materials['Material.025']}
          position={[-0.546, 0.662, 1.007]}
          rotation={[-1.65, 1.469, -1.446]}
          scale={[0.1, 0.11, 0.068]}
        />
        <mesh
          name="Object_782_OnTheFly-bg_0"
          
          
          geometry={nodes['Object_782_OnTheFly-bg_0'].geometry}
          material={materials['Material.074_40']}
          position={[-0.511, 0.669, 1.181]}
          rotation={[-1.399, -0.165, -1.386]}
          scale={[0.022, 0.015, 0.025]}
        />
        <mesh
          name="Plane_Material053_0"
          
          
          geometry={nodes.Plane_Material053_0.geometry}
          material={materials['Material.074_21']}
          position={[-0.521, 0.651, 1.48]}
          rotation={[-Math.PI / 2, 0, -3.136]}
          scale={[0.093, 0.169, 0.146]}
        />
        <mesh
          name="psuback_psuback_0"
          
          
          geometry={nodes.psuback_psuback_0.geometry}
          material={materials['Material.074_13']}
          position={[-0.238, 0.715, 1.834]}
          rotation={[0, -1.565, 0]}
          scale={[0.065, 0.072, 0.044]}
        />
        <mesh
          name="rgb-hdd-cover-aorus-v1_rgb-hdd-cover-aorus-v1_0"
          
          
          geometry={nodes['rgb-hdd-cover-aorus-v1_rgb-hdd-cover-aorus-v1_0'].geometry}
          material={materials['Material.074_9']}
          position={[-0.362, 0.721, 1.764]}
          rotation={[Math.PI, -0.006, Math.PI]}
          scale={[0.027, 0.045, 0.041]}
        />
        <mesh
          name="test-aorus-m2-souris-aorus-rgb2_test-aorus-m2-souris-aorus-rgb2"
          
          
          geometry={
            nodes['test-aorus-m2-souris-aorus-rgb2_test-aorus-m2-souris-aorus-rgb2'].geometry
          }
          material={materials['Material.074_18']}
          position={[-0.345, 0.803, 1.925]}
          rotation={[Math.PI, -0.006, Math.PI]}
          scale={[0.026, 0.043, 0.039]}
        />
        <mesh
          name="Text_Material046_0"
          
          
          geometry={nodes.Text_Material046_0.geometry}
          material={materials['Material.046']}
          position={[-0.325, 0.924, 1.804]}
          rotation={[Math.PI, -0.006, -Math.PI / 2]}
          scale={[0.003, 0.002, 0.003]}
        />
        <mesh
          name="Object_1056_Material073_0"
          
          
          geometry={nodes.Object_1056_Material073_0.geometry}
          material={materials['Material.073']}
          position={[-0.539, 0.681, 1.015]}
          rotation={[-1.456, -0.104, -1.448]}
          scale={[0.003, 0.002, 0.003]}
        />
        <mesh
          name="Torus_Material013_0"
          
          
          geometry={nodes.Torus_Material013_0.geometry}
          material={materials['Material.013']}
          position={[-0.483, 1.053, 1.894]}
          rotation={[-Math.PI / 2, 0, -3.136]}
          scale={[0.002, 0.004, 0.004]}
        />
        <mesh
          name="Torus001_Material032_0"
          
          
          geometry={nodes.Torus001_Material032_0.geometry}
          material={materials['Material.032']}
          position={[-0.483, 1.053, 1.913]}
          rotation={[-Math.PI / 2, 0, -3.136]}
          scale={[0.002, 0.004, 0.004]}
        />
        <mesh
          name="usb_usb_0"
          
          
          geometry={nodes.usb_usb_0.geometry}
          material={materials['Material.074_14']}
          position={[-0.484, 1.054, 1.766]}
          rotation={[-Math.PI / 2, 0, -1.565]}
          scale={[0.008, 0.005, 0.009]}
        />
        <mesh
          name="NurbsPath_Material001_0"
          
          
          geometry={nodes.NurbsPath_Material001_0.geometry}
          material={materials['Material.005']}
          position={[0.595, 1.17, 1.544]}
          rotation={[-Math.PI / 2, 0, -1.633]}
          scale={[0.013, 0.034, 0.043]}
        />
        <mesh
          name="Cube_Material002_0001"
          
          
          geometry={nodes.Cube_Material002_0001.geometry}
          material={materials['Material.008']}
          position={[0.567, 0.927, -2.383]}
          rotation={[-Math.PI / 2, 0, -0.066]}
          scale={[0.339, 0.012, 0.175]}
        />
        <mesh
          name="Ultrawide_Monitor_Body_0"
          
          
          geometry={nodes.Ultrawide_Monitor_Body_0.geometry}
          material={materials.Body}
          position={[1.441, 0.91, -2.246]}
          rotation={[-Math.PI / 2, 0.001, -Math.PI / 2]}
          scale={[0.01, 0.314, 0.19]}
        />
        <mesh
          name="Ultrawide_Monitor_Lights_0"
          
          
          geometry={nodes.Ultrawide_Monitor_Lights_0.geometry}
          material={materials.Lights}
          position={[1.441, 0.91, -2.246]}
          rotation={[-Math.PI / 2, 0.001, -Math.PI / 2]}
          scale={[0.01, 0.314, 0.19]}
        />
        <mesh
          name="ClickableObject"
          
          
          geometry={nodes.Ultrawide_Monitor_Screen_0.geometry}
          material={materials.Screen}
          position={[1.441, 0.91, -2.246]}
          rotation={[-Math.PI / 2, 0.001, -Math.PI / 2]}
          scale={[0.01, 0.314, 0.19]}
        />
        <mesh
          name="Object_9001"
          
          
          geometry={nodes.Object_9001.geometry}
          material={materials.Logo_AMD}
          position={[1.924, 0.636, 0.813]}
          rotation={[Math.PI, 0.054, -Math.PI]}
          scale={[0.019, 0.018, 0.02]}
        />
        <mesh
          name="Object_12001"
          
          
          geometry={nodes.Object_12001.geometry}
          material={materials['material.002']}
          position={[1.381, 0.638, 1.011]}
          rotation={[Math.PI, 0.054, -Math.PI]}
          scale={[0.004, 0.003, 0.004]}
        />
        <mesh
          name="Object_24003"
          
          
          geometry={nodes.Object_24003.geometry}
          material={materials.Teks_Bawah}
          position={[1.917, 0.605, 1.077]}
          rotation={[Math.PI, 0.054, 0]}
          scale={[0.045, 0.041, 0.047]}
        />
        <mesh
          name="Object_19"
          
          
          geometry={nodes.Object_19.geometry}
          material={materials.Lightbar}
          position={[1.486, 0.638, 0.989]}
          rotation={[Math.PI, 0.801, -Math.PI]}
          scale={[0.026, 0.023, 0.026]}
        />
        <mesh
          name="Object_15"
          
          
          geometry={nodes.Object_15.geometry}
          material={materials.Merah}
          position={[1.486, 0.638, 0.989]}
          rotation={[Math.PI, 0.801, -Math.PI]}
          scale={[0.026, 0.023, 0.026]}
        />
        <mesh
          name="Object_28001"
          
          
          geometry={nodes.Object_28001.geometry}
          material={materials.Metal_1}
          position={[1.937, 0.665, 1.1]}
          rotation={[-2.965, 0.053, 3.132]}
          scale={[0.192, 0.177, 0.193]}
        />
        <mesh
          name="Object_31001"
          
          
          geometry={nodes.Object_31001.geometry}
          material={materials.Layar}
          position={[1.635, 0.865, 1.123]}
          rotation={[1.746, 0.01, -3.088]}
          scale={[0.185, 0.193, 0.17]}
        />
        <mesh
          name="Object_33002"
          
          
          geometry={nodes.Object_33002.geometry}
          material={materials.Touchpad}
          position={[1.635, 0.865, 1.123]}
          rotation={[1.746, 0.01, -3.088]}
          scale={[0.185, 0.193, 0.17]}
        />
        <mesh
          name="Object_37"
          
          
          geometry={nodes.Object_37.geometry}
          material={materials.Logo}
          position={[1.635, 0.865, 1.123]}
          rotation={[1.746, 0.01, -3.088]}
          scale={[0.185, 0.193, 0.17]}
        />
        <mesh
          name="Object_39001"
          
          
          geometry={nodes.Object_39001.geometry}
          material={materials.Web_Cam}
          position={[1.635, 0.865, 1.123]}
          rotation={[1.746, 0.01, -3.088]}
          scale={[0.185, 0.193, 0.17]}
        />
        <mesh
          name="Object_42001"
          
          
          geometry={nodes.Object_42001.geometry}
          material={materials.Logo_Text}
          position={[1.874, 0.676, 1.102]}
          rotation={[1.746, 0.01, -3.088]}
          scale={[0.011, 0.011, 0.01]}
        />
        <mesh
          name="Object_49001"
          
          
          geometry={nodes.Object_49001.geometry}
          material={materials.Metal_2}
          position={[1.649, 0.636, 0.87]}
          rotation={[Math.PI, 0.054, -Math.PI]}
          scale={[0.185, 0.169, 0.193]}
        />
        <mesh
          name="Object_54001"
          
          
          geometry={nodes.Object_54001.geometry}
          material={materials.Keyboard}
          position={[1.851, 0.638, 0.885]}
          rotation={[Math.PI, 0.054, -Math.PI]}
          scale={[0.014, 0.013, 0.014]}
        />
        <mesh
          name="Object_131001"
          
          
          geometry={nodes.Object_131001.geometry}
          material={materials.Bawah}
          position={[1.392, 0.638, 0.893]}
          rotation={[Math.PI, 0.054, -Math.PI]}
          scale={[0.014, 0.013, 0.014]}
        />
        <mesh
          name="Object_158"
          
          
          geometry={nodes.Object_158.geometry}
          material={materials['Material.009']}
          position={[1.649, 0.608, 0.867]}
          rotation={[0, -0.054, Math.PI]}
          scale={[0.185, 0.169, 0.193]}
        />
        <mesh
          name="Object_162"
          
          
          geometry={nodes.Object_162.geometry}
          material={materials.Hole}
          position={[1.649, 0.608, 0.867]}
          rotation={[0, -0.054, Math.PI]}
          scale={[0.185, 0.169, 0.193]}
        />
        <mesh
          name="Object_172"
          
          
          geometry={nodes.Object_172.geometry}
          material={materials.material_0}
          position={[1.291, 0.637, 0.628]}
          rotation={[0, -0.702, Math.PI]}
          scale={[0.331, 0.169, 0]}
        />
        <mesh
          name="Object_175001"
          
          
          geometry={nodes.Object_175001.geometry}
          material={materials.Logo_RTX}
          position={[1.87, 0.636, 0.81]}
          rotation={[Math.PI, 0.054, -Math.PI]}
          scale={[0.019, 0.018, 0.02]}
        />
        <mesh
          name="Object_184"
          
          
          geometry={nodes.Object_184.geometry}
          material={materials.Indikator}
          position={[1.577, 0.638, 1.046]}
          rotation={[Math.PI, 0.054, -Math.PI]}
          scale={[0.011, 0.01, 0.011]}
        />
        <mesh
          name="Object_178"
          
          
          geometry={nodes.Object_178.geometry}
          material={materials.Logo_ROG}
          position={[1.816, 0.642, 1.115]}
          rotation={[0.226, -0.053, 0.013]}
          scale={[0.185, 0.17, 0.192]}
        />
        <mesh
          name="Tastatur_Tastatur_F����chen_0"
          
          
          geometry={nodes['Tastatur_Tastatur_F����chen_0'].geometry}
          material={materials.Tastatur_Fchen}
          position={[0.545, 0.619, -2.078]}
          rotation={[-1.572, -0.002, -0.022]}
          scale={[0.131, 0.126, 0.086]}
        />
        <mesh
          name="Tastatur_Tastatur_Seite_0"
          
          
          geometry={nodes.Tastatur_Tastatur_Seite_0.geometry}
          material={materials['Tastatur_Seite.001']}
          position={[0.545, 0.619, -2.078]}
          rotation={[-1.572, -0.002, -0.022]}
          scale={[0.131, 0.126, 0.086]}
        />
        <mesh
          name="Tastatur_Tastatur_Untergrund_0"
          
          
          geometry={nodes.Tastatur_Tastatur_Untergrund_0.geometry}
          material={materials.Tastatur_Untergrund}
          position={[0.545, 0.619, -2.078]}
          rotation={[-1.572, -0.002, -0.022]}
          scale={[0.131, 0.126, 0.086]}
        />
        <mesh
          name="Tastatur_Tastatur_Unterseite_0"
          
          
          geometry={nodes.Tastatur_Tastatur_Unterseite_0.geometry}
          material={materials['Tastatur_Unterseite.001']}
          position={[0.545, 0.619, -2.078]}
          rotation={[-1.572, -0.002, -0.022]}
          scale={[0.131, 0.126, 0.086]}
        />
        <mesh
          name="Tasten_Tasten_2_0"
          
          
          geometry={nodes.Tasten_Tasten_2_0.geometry}
          material={materials['Tasten_2.001']}
          position={[0.545, 0.619, -2.078]}
          rotation={[-1.474, -0.004, -0.022]}
          scale={[0.131, 0.126, 0.086]}
        />
        <mesh
          name="Tasten_Kappen_Tasten_Emission_0"
          
          
          geometry={nodes.Tasten_Kappen_Tasten_Emission_0.geometry}
          material={materials.Tasten_Emission}
          position={[0.545, 0.619, -2.078]}
          rotation={[-1.474, -0.004, -0.022]}
          scale={[0.131, 0.126, 0.086]}
        />
        <mesh
          name="Tasten_Kappen_Tasten_0"
          
          
          geometry={nodes.Tasten_Kappen_Tasten_0.geometry}
          material={materials.Tasten}
          position={[0.545, 0.619, -2.078]}
          rotation={[-1.474, -0.004, -0.022]}
          scale={[0.131, 0.126, 0.086]}
        />
        <mesh
          name="Cube001_ac_0"
          
          
          geometry={nodes.Cube001_ac_0.geometry}
          material={materials['material.003']}
          position={[-4.335, 1.977, 2.207]}
          rotation={[-Math.PI / 2, 0, 1.486]}
          scale={[0.696, 0.243, 0.224]}
        />
        <mesh
          name="Object_10001"
          
          
          geometry={nodes.Object_10001.geometry}
          material={materials['Tastatur_Unterseite.002']}
          position={[1.483, 0.626, -2.037]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[0.107, 0.084, 0.12]}
        />
        <mesh
          name="Object_14001"
          
          
          geometry={nodes.Object_14001.geometry}
          material={materials['Material.010']}
          position={[1.483, 0.626, -2.037]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[0.107, 0.084, 0.12]}
        />
        <mesh
          name="Object_24004"
          
          
          geometry={nodes.Object_24004.geometry}
          material={materials['Tastatur_Seite.002']}
          position={[1.483, 0.626, -2.037]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[0.107, 0.084, 0.12]}
        />
        <mesh
          name="Object_30001"
          
          
          geometry={nodes.Object_30001.geometry}
          material={materials['Material.011']}
          position={[1.483, 0.626, -2.037]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[0.107, 0.084, 0.12]}
        />
        <mesh
          name="Object_420001"
          
          
          geometry={nodes.Object_420001.geometry}
          material={materials['Tasten.001']}
          position={[1.501, 0.625, -2.024]}
          rotation={[-1.474, 0, 0]}
          scale={[0.079, 0.085, 0.12]}
        />
        <mesh
          name="Object_604001"
          
          
          geometry={nodes.Object_604001.geometry}
          material={materials['Material.020']}
          position={[1.483, 0.629, -2.039]}
          rotation={[-1.474, 0, 0]}
          scale={[0.107, 0.085, 0.12]}
        />
        <mesh
          name="Object_49003"
          
          
          geometry={nodes.Object_49003.geometry}
          material={materials['Tasten_2.002']}
          position={[1.483, 0.626, -2.04]}
          rotation={[-1.474, 0, 0]}
          scale={[0.107, 0.085, 0.12]}
        />
        <mesh
          name="Object_55001"
          
          
          geometry={nodes.Object_55001.geometry}
          material={materials['Material.014']}
          position={[1.483, 0.626, -2.04]}
          rotation={[-1.474, 0, 0]}
          scale={[0.107, 0.085, 0.12]}
        />
        <mesh
          name="Object_59001"
          
          
          geometry={nodes.Object_59001.geometry}
          material={materials['Material.027']}
          position={[1.483, 0.626, -2.04]}
          rotation={[-1.474, 0, 0]}
          scale={[0.107, 0.085, 0.12]}
        />
        <mesh
          name="Object_65001"
          
          
          geometry={nodes.Object_65001.geometry}
          material={materials['Material.022']}
          position={[1.483, 0.626, -2.04]}
          rotation={[-1.474, 0, 0]}
          scale={[0.107, 0.085, 0.12]}
        />
        <mesh
          name="Object_67001"
          
          
          geometry={nodes.Object_67001.geometry}
          material={materials['Material.015']}
          position={[1.483, 0.626, -2.04]}
          rotation={[-1.474, 0, 0]}
          scale={[0.107, 0.085, 0.12]}
        />
        <mesh
          name="Object_81003"
          
          
          geometry={nodes.Object_81003.geometry}
          material={materials['Material.016']}
          position={[1.483, 0.626, -2.04]}
          rotation={[-1.474, 0, 0]}
          scale={[0.107, 0.085, 0.12]}
        />
        <mesh
          name="Object_93002"
          
          
          geometry={nodes.Object_93002.geometry}
          material={materials['Material.018']}
          position={[1.483, 0.626, -2.04]}
          rotation={[-1.474, 0, 0]}
          scale={[0.107, 0.085, 0.12]}
        />
        <mesh
          name="Object_97001"
          
          
          geometry={nodes.Object_97001.geometry}
          material={materials['Material.012']}
          position={[1.483, 0.626, -2.04]}
          rotation={[-1.474, 0, 0]}
          scale={[0.107, 0.085, 0.12]}
        />
        <mesh
          name="Object_103001"
          
          
          geometry={nodes.Object_103001.geometry}
          material={materials['Material.019']}
          position={[1.483, 0.626, -2.04]}
          rotation={[-1.474, 0, 0]}
          scale={[0.107, 0.085, 0.12]}
        />
        <mesh
          name="Object_782001"
          
          
          geometry={nodes.Object_782001.geometry}
          material={materials['OnTheFly-bg']}
          position={[1.668, 0.636, -2.079]}
          rotation={[0.082, 0, 0]}
          scale={[0.026, 0.029, 0.02]}
        />
        <mesh
          name="Object_954001"
          
          
          geometry={nodes.Object_954001.geometry}
          material={materials['Material.021']}
          position={[1.251, 0.627, -2.002]}
          rotation={[-1.38, 1.538, 1.475]}
          scale={[0.005, 0.007, 0.005]}
        />
        <mesh
          name="Object_1056001"
          
          
          geometry={nodes.Object_1056001.geometry}
          material={materials['Material.028']}
          position={[1.491, 0.649, -2.045]}
          rotation={[0.046, 0, 0]}
          scale={[0.003, 0.004, 0.003]}
        />
        <mesh
          name="adapter_adapter_0"
          
          
          geometry={nodes.adapter_adapter_0.geometry}
          material={materials.adapter}
          position={[0.932, 0.61, -2.078]}
          scale={0.008}
        />
        <mesh
          name="mouse_mouse_0"
          
          
          geometry={nodes.mouse_mouse_0.geometry}
          material={materials.mouse}
          position={[0.932, 0.61, -2.078]}
          rotation={[0, -0.203, 0]}
          scale={0.008}
        />
        <mesh
          name="bu001"
          
          
          geometry={nodes.bu001.geometry}
          material={materials.bu}
          position={[-0.653, 0.555, -6.301]}
          rotation={[-3.11, 0.013, 3.141]}
          scale={[1.124, 0.811, 1.186]}
        />
        <mesh
          name="zhuoyi001"
          
          
          geometry={nodes.zhuoyi001.geometry}
          material={materials.zhuoyi}
          position={[-0.656, 0.533, -6.291]}
          rotation={[-3.11, 0.013, 3.141]}
          scale={[1.124, 0.811, 1.186]}
        />
        <mesh
          name="对象004001"
          
          
          geometry={nodes.对象004001.geometry}
          material={materials.niunai}
          position={[-0.649, 0.398, -6.226]}
          rotation={[-3.11, 0.013, 3.141]}
          scale={[1.124, 0.811, 1.186]}
        />
        <mesh
          name="Logo_Material_0"
          
          
          geometry={nodes.Logo_Material_0.geometry}
          material={materials['Material.026']}
          position={[4.977, 0.914, 3.629]}
          rotation={[-Math.PI / 2, 0, -2.002]}
          scale={[0.007, 0.008, 0.01]}
        />
        <mesh
          name="Object_26003"
          
          
          geometry={nodes.Object_26003.geometry}
          material={materials['Material.041']}
          position={[4.552, 0.734, 4.193]}
          rotation={[Math.PI, -1.179, Math.PI]}
          scale={[0.302, 0.433, 0.203]}
        />
        <mesh
          name="Object_28004"
          
          
          geometry={nodes.Object_28004.geometry}
          material={materials['Material.036']}
          position={[4.805, 1.004, 4.346]}
          rotation={[Math.PI, -1.179, Math.PI]}
          scale={[0.302, 0.433, 0.203]}
        />
        <mesh
          name="Object_29"
          
          
          geometry={nodes.Object_29.geometry}
          material={materials['Fer.001']}
          position={[4.805, 1.004, 4.346]}
          rotation={[Math.PI, -1.179, Math.PI]}
          scale={[0.302, 0.433, 0.203]}
        />
        <mesh
          name="Object_30003"
          
          
          geometry={nodes.Object_30003.geometry}
          material={materials['Material.047']}
          position={[4.805, 1.004, 4.346]}
          rotation={[Math.PI, -1.179, Math.PI]}
          scale={[0.302, 0.433, 0.203]}
        />
        <mesh
          name="Object_31002"
          
          
          geometry={nodes.Object_31002.geometry}
          material={materials['Material.038']}
          position={[4.805, 1.004, 4.346]}
          rotation={[Math.PI, -1.179, Math.PI]}
          scale={[0.302, 0.433, 0.203]}
        />
        <mesh
          name="Object_32003"
          
          
          geometry={nodes.Object_32003.geometry}
          material={materials['Material.050']}
          position={[4.805, 1.004, 4.346]}
          rotation={[Math.PI, -1.179, Math.PI]}
          scale={[0.302, 0.433, 0.203]}
        />
        <mesh
          name="Object_33003"
          
          
          geometry={nodes.Object_33003.geometry}
          material={materials['Material.051']}
          position={[4.805, 1.004, 4.346]}
          rotation={[Math.PI, -1.179, Math.PI]}
          scale={[0.302, 0.433, 0.203]}
        />
        <mesh
          name="Object_4003"
          
          
          geometry={nodes.Object_4003.geometry}
          material={materials['Material.029']}
          position={[4.597, 0.489, 4.261]}
          rotation={[Math.PI, -1.179, Math.PI]}
          scale={[0.063, 0.09, 0.042]}
        />
        <mesh
          name="Object_22003"
          
          
          geometry={nodes.Object_22003.geometry}
          material={materials['Material.040']}
          position={[4.597, 0.489, 4.261]}
          rotation={[Math.PI, -1.179, Math.PI]}
          scale={[0.063, 0.09, 0.042]}
        />
        <mesh
          name="Object_37001"
          
          
          geometry={nodes.Object_37001.geometry}
          material={materials.Carbone}
          position={[4.597, 0.489, 4.261]}
          rotation={[Math.PI, -1.179, Math.PI]}
          scale={[0.063, 0.09, 0.042]}
        />
        <mesh
          name="Object_39002"
          
          
          geometry={nodes.Object_39002.geometry}
          material={materials['Material.052']}
          position={[4.689, 0.489, 4.299]}
          rotation={[Math.PI, -1.179, Math.PI]}
          scale={[0.302, 0.433, 0.203]}
        />
        <mesh
          name="Object_8003"
          
          
          geometry={nodes.Object_8003.geometry}
          material={materials['Material.031']}
          position={[4.689, 0.489, 4.299]}
          rotation={[Math.PI, -1.179, Math.PI]}
          scale={[0.302, 0.433, 0.203]}
        />
        <mesh
          name="Object_9003"
          
          
          geometry={nodes.Object_9003.geometry}
          material={materials['Material.033']}
          position={[4.689, 0.489, 4.299]}
          rotation={[Math.PI, -1.179, Math.PI]}
          scale={[0.302, 0.433, 0.203]}
        />
        <mesh
          name="Object_11001"
          
          
          geometry={nodes.Object_11001.geometry}
          material={materials['Material.035']}
          position={[4.689, 0.489, 4.299]}
          rotation={[Math.PI, -1.179, Math.PI]}
          scale={[0.302, 0.433, 0.203]}
        />
        <mesh
          name="Object_13001"
          
          
          geometry={nodes.Object_13001.geometry}
          material={materials['Volant.003']}
          position={[4.689, 0.488, 4.299]}
          rotation={[3.111, -1.179, 3.102]}
          scale={[0.302, 0.433, 0.203]}
        />
        <mesh
          name="Object_6001"
          
          
          geometry={nodes.Object_6001.geometry}
          material={materials['Material.030']}
          position={[4.597, 0.489, 4.261]}
          rotation={[Math.PI, -1.179, Math.PI]}
          scale={[0.302, 0.433, 0.203]}
        />
        <mesh
          name="Object_10004"
          
          
          geometry={nodes.Object_10004.geometry}
          material={materials['0002_PS4_04_4']}
          position={[4.916, 0.915, 4.673]}
          rotation={[-Math.PI / 2, 0, -2.114]}
          scale={0.001}
        />
        <mesh
          name="Object_11002"
          
          
          geometry={nodes.Object_11002.geometry}
          material={materials['0002_PS4_04_5']}
          position={[4.916, 0.915, 4.673]}
          rotation={[-Math.PI / 2, 0, -2.114]}
          scale={0.001}
        />
        <mesh
          name="Object_12004"
          
          
          geometry={nodes.Object_12004.geometry}
          material={materials['0004_PS4_05']}
          position={[4.916, 0.915, 4.673]}
          rotation={[-Math.PI / 2, 0, -2.114]}
          scale={0.001}
        />
        <mesh
          name="Object_13002"
          
          
          geometry={nodes.Object_13002.geometry}
          material={materials['material.004']}
          position={[4.916, 0.915, 4.673]}
          rotation={[-Math.PI / 2, 0, -2.114]}
          scale={0.001}
        />
        <mesh
          name="Object_14003"
          
          
          geometry={nodes.Object_14003.geometry}
          material={materials['material_14.001']}
          position={[4.916, 0.915, 4.673]}
          rotation={[-Math.PI / 2, 0, -2.114]}
          scale={0.001}
        />
        <mesh
          name="Object_15002"
          
          
          geometry={nodes.Object_15002.geometry}
          material={materials.Color_008}
          position={[4.916, 0.915, 4.673]}
          rotation={[-Math.PI / 2, 0, -2.114]}
          scale={0.001}
        />
        <mesh
          name="Object_16003"
          
          
          geometry={nodes.Object_16003.geometry}
          material={materials.Color_I11}
          position={[4.916, 0.915, 4.673]}
          rotation={[-Math.PI / 2, 0, -2.114]}
          scale={0.001}
        />
        <mesh
          name="Object_2002"
          
          
          geometry={nodes.Object_2002.geometry}
          material={materials['0000_PS4_1']}
          position={[4.916, 0.915, 4.673]}
          rotation={[-Math.PI / 2, 0, -2.114]}
          scale={0.001}
        />
        <mesh
          name="Object_3"
          
          
          geometry={nodes.Object_3.geometry}
          material={materials['0000_PS4_1_1']}
          position={[4.916, 0.915, 4.673]}
          rotation={[-Math.PI / 2, 0, -2.114]}
          scale={0.001}
        />
        <mesh
          name="Object_4004"
          
          
          geometry={nodes.Object_4004.geometry}
          material={materials['0001_PS4_02']}
          position={[4.916, 0.915, 4.673]}
          rotation={[-Math.PI / 2, 0, -2.114]}
          scale={0.001}
        />
        <mesh
          name="Object_5001"
          
          
          geometry={nodes.Object_5001.geometry}
          material={materials['0001_PS4_02_1']}
          position={[4.916, 0.915, 4.673]}
          rotation={[-Math.PI / 2, 0, -2.114]}
          scale={0.001}
        />
        <mesh
          name="Object_6002"
          
          
          geometry={nodes.Object_6002.geometry}
          material={materials['0002_PS4_04']}
          position={[4.916, 0.915, 4.673]}
          rotation={[-Math.PI / 2, 0, -2.114]}
          scale={0.001}
        />
        <mesh
          name="Object_7"
          
          
          geometry={nodes.Object_7.geometry}
          material={materials['0002_PS4_04_1']}
          position={[4.916, 0.915, 4.673]}
          rotation={[-Math.PI / 2, 0, -2.114]}
          scale={0.001}
        />
        <mesh
          name="Object_8004"
          
          
          geometry={nodes.Object_8004.geometry}
          material={materials['0002_PS4_04_2']}
          position={[4.916, 0.915, 4.673]}
          rotation={[-Math.PI / 2, 0, -2.114]}
          scale={0.001}
        />
        <mesh
          name="Object_9004"
          
          
          geometry={nodes.Object_9004.geometry}
          material={materials['0002_PS4_04_3']}
          position={[4.916, 0.915, 4.673]}
          rotation={[-Math.PI / 2, 0, -2.114]}
          scale={0.001}
        />
        <mesh
          name="vending_machine_vending_0"
          
          
          geometry={nodes.vending_machine_vending_0.geometry}
          material={materials.vending}
          position={[-0.498, 0.998, 6.546]}
          rotation={[0, 0.012, 0]}
          scale={0.001}
        />
      </a.group>
    </a.group>
  )
}





export default Room;
